version: 2
jobs:
  build:
    working_directory: ~/News-Feed
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx2g
    steps:
      - checkout
      - run:
          name: Get Guardian API Key
          command: echo "GUARDIAN_API_KEY=$GUARDIAN_API_KEY" >> ~/News-Feed/secrets.properties
      - run:
          name: Get News API Key
          command: echo "NEWS_API_KEY=$NEWS_API_KEY" >> ~/News-Feed/secrets.properties
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
      - run:
          name: Build Debug
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-result
